CREATE TABLE DEPT(ID INT PRIMARY KEY,DEPT_NAME VARCHAR(20),DESCRIPTION VARCHAR(20));
CREATE TABLE EMPLOYEE(ID INT,NAME VARCHAR(20),EMAIL VARCHAR(20),SALARY INT,DEPT INT FOREIGN KEY REFERENCES DEPT(ID),GENDER VARCHAR(10),JOINING_DATE DATETIME);
INSERT INTO DEPT VALUES(1,'HR','MANAGMENTS')
INSERT INTO DEPT VALUES(2,'DEVELOPER','CODING')
INSERT INTO DEPT VALUES(3,'TESTER','TESTING')
INSERT INTO DEPT VALUES(4,'SKILL DEVELOPMENT','IMPROVE SKILLS')
INSERT INTO DEPT VALUES(5,'SWEEPER DEPARTMENT','HOUSE KEEPING')

SELECT * FROM DEPT;
SELECT TOP 1 SALARY FROM(SELECT DISTINCT TOP 2 SALARY FROM EMPLOYEE ORDER BY SALARY DESC)RESULT ORDER BY SALARY ASC;

SELECT * FROM EMPLOYEE;
INSERT INTO EMPLOYEE VALUES(101,'VIKASH AHLAWAT','VIKASH123@GMIAIL.COM',55000,4,'MALE','2012-05-15')
INSERT INTO EMPLOYEE VALUES(102,'NIKITA JAIN','NIKITA13@GMIAIL.COM',50000,1,'FEMALE','2015-09-25')
INSERT INTO EMPLOYEE VALUES(103,'ASHISH KUMAR','ASHISH243@GMIAIL.COM',45000,2,'MALE','2018-09-05')
INSERT INTO EMPLOYEE VALUES(104,'PANKAJ SHARMA','PANKAJ143@GMIAIL.COM',35000,2,'MALE','2020-05-15')
INSERT INTO EMPLOYEE VALUES(105,'ANJALI KUMARI','ANJALI222@GMIAIL.COM',50000,3,'FEMALE','2019-12-07');
INSERT INTO EMPLOYEE VALUES(106,'PANKAJ SHARMA','PANKAJ143@GMIAIL.COM',35000,2,'MALE','2020-05-15')

-----------3RD HIGHEST SALARY---------------- 
SELECT MAX(SALARY)AS SALARY FROM EMPLOYEE WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEE WHERE SALARY<(SELECT MAX(SALARY) FROM EMPLOYEE));
-----------4RD HIGHEST----------
SELECT TOP 1 SALARY FROM(SELECT DISTINCT TOP 4 SALARY FROM EMPLOYEE ORDER BY SALARY DESC)RESULT ORDER BY SALARY;
------------2-----------
SELECT * FROM EMPLOYEE WHERE NAME LIKE 'A____';
-----------3-----------
SELECT * FROM EMPLOYEE WHERE JOINING_DATE BETWEEN '2015-01-01' AND GETDATE();
-----------4-----------
SELECT * FROM EMPLOYEE AS A
FULL OUTER JOIN
DEPT AS B ON A.DEPT=B.ID;
----------5-----------
DECLARE @EMAIL VARCHAR(MAX)
SELECT @EMAIL=COALESCE(@EMAIL+' , ','')+ EMAIL FROM EMPLOYEE
PRINT @EMAIL
-----------------------------
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPT;

-------------6---------------------
CREATE TABLE TEAM(ID INT,NAME VARCHAR(20),PLAYER_ID INT,TEAM VARCHAR(20),CITY VARCHAR(20));
INSERT INTO TEAM VALUES(1,'SACHIN',99,'MUMBAI','CHENNAI')
INSERT INTO TEAM VALUES(1,'SACHIN',99,'MUMBAI','CHENNAI')
INSERT INTO TEAM VALUES(2,'ROHIT SHARMA',45,'MUMBAI','RANCHI')
INSERT INTO TEAM VALUES(3,'DHONI',25,'CHENNAI','RANCHI')
INSERT INTO TEAM VALUES(2,'ROHIT SHARMA',45,'MUMBAI','RANCHI')
INSERT INTO TEAM VALUES(4,'VIRAT','10','AGRA','DELHI')
INSERT INTO TEAM VALUES(3,'DHONI',25,'CHENNAI','RANCHI')
WITH TEAMCTE AS
(
SELECT *,ROW_NUMBER()OVER (PARTITION BY ID ORDER BY ID)AS NUMBER FROM TEAM
)
DELETE FROM TEAMCTE WHERE NUMBER>1
SELECT * FROM TEAM;